#!/bin/bash

echo "CONTINUEING WILL DELETE EXISTING NEOVIM CONFIG!!!"
read a

TARGET="$HOME/.config/nvim"

rm -rf "$TARGET"

ln -s "$(pwd)" "$TARGET"

echo "Created symlink"

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo "installed vimplug"
